version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: soa-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_MULTIPLE_DATABASES: db_user,db_event,db_booking
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always

volumes:
  pgdata: